name: Build and publish to docs

on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Ensure docs folder exists
        run: mkdir -p docs

      - name: Copy build to docs
        run: rsync -a --delete build/ docs/

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Force add build folder to commit (override .gitignore)
        run: |
          git add -f build

      - name: Commit and push docs
        run: |
          git add docs
          if ! git diff --cached --quiet; then
            git commit -m "chore(ci): build site and publish to docs"
            git push origin docs --force
          else
            echo "No changes to commit."
          fi
